### ISSUE TITLE
How to setup iSponsorBlockTV addon?

### ISSUE THREAD

**Issue by evlo** [bertybuttface/addons#24]
I have
1. added addon to HA
2. open configuration and put in
```
apikey: AIzaSyBsQgGwi9oj3Z2LAwz9Sm7EQHCUN0
devices:
  - screen_id: "447989516299"
    name: LivingRoom TV
    offset: 0
channel_whitelist: []
skip_categories:
  - sponsor
  - selfpromo
  - exclusive_access
  - interaction
  - poi_highlight
  - intro
  - outro
  - preview
  - filler
  - music_offtopic
skip_count_tracking: false
mute_ads: true
skip_ads: true

```
screen_id I used this 
![20240216_231126](https://github.com/bertybuttface/addons/assets/8813196/add1c245-86dc-43e6-b097-c6a4a297071b)
from the TV, it changes a lot, probably evry youtube app stat on the TV

4. for the api key i did use 
https://console.cloud.google.com/apis/
enabled YouTube Data API v3
and copied api key generated in this section
![image](https://github.com/bertybuttface/addons/assets/8813196/76e6c40c-5cf2-4437-aaf0-99e87d0a4733)

5. after setting the config I restarted the addon and the log i did get
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun isponsorblocktv (no readiness notification)
s6-rc: info: service legacy-services successfully started
[23:13:50] INFO: Starting...
[02/16/24 23:13:54] INFO     LivingRoom TV Starting device                      
                    INFO     LivingRoom TV Refreshed auth, lounge id token      
                                           AGdO5p_j4bxIWkT7h-TWOsqgoUdf7i1K0xPHo
                                           jvLWAJhkWg8yae5YntRX46NC9tZ1nNv2DE1wq
                                           lA8hVdzh1FXqcvDA    
```

there is nothing in linked devices on the TV

sadly this cannot be used as a guide as it is wrong, but I was not able to find any real guide - so what did i do wrong

I guess there is also a way to connect to the addon docker using ssh to initiate setup?
I can connect to home assistant using SSH and I do see the addon
![image](https://github.com/bertybuttface/addons/assets/8813196/2800fd3b-cc1b-48f0-b88e-bb5de3b9a661)
